name: "Pie Build Uploader"
description: "Upload iOS/Android simulator builds to Pie"
author: "Pie"

inputs:
  pie_api_key:
    description: "Pie API Key for authentication"
    required: true
  build_path:
    description: "Path to the build file (APK, IPA, or AAB)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check build file exists
      shell: bash
      id: build_check
      run: |
        if [ -d "${{ inputs.build_path }}" ]; then
          echo "Directory detected, creating zip archive..."
          dir_name=$(basename "${{ inputs.build_path }}")
          zip_path="${{ inputs.build_path }}.zip"
          cd "$(dirname "${{ inputs.build_path }}")"
          zip -r "$zip_path" "$dir_name"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to create zip archive"
            exit 1
          fi
          echo "Created zip archive at $zip_path"
          echo "build_path=$zip_path" >> $GITHUB_OUTPUT
          echo "::set-output name=build_path::$zip_path"
        else
          echo "build_path=${{ inputs.build_path }}" >> $GITHUB_OUTPUT
        fi

    - name: Upload build to Pie
      shell: bash
      run: |

        if [ ! -f "${{ steps.build_check.outputs.build_path }}" ]; then
          echo "Error: Build file not found at ${{ steps.build_check.outputs.build_path }}"
          exit 1
        fi

        # Check file extension
        if [[ ! "${{ steps.build_check.outputs.build_path }}" =~ \.(apk|ipa|aab|zip)$ ]]; then
          echo "Error: Build file must be an APK, IPA, AAB, or ZIP file"
          exit 1
        fi

        # Upload the build using curl with multipart form-data
        response=$(curl -X POST \
          -H "Authorization: Bearer ${{ inputs.pie_api_key }}" \
          -F "file=@${{ steps.build_check.outputs.build_path }}" \
          https://api.pie.inc/v1/app/builds)

        # Check if upload was successful
        if [ $? -ne 0 ]; then
          echo "Error: Failed to upload build to Pie API"
          exit 1
        fi

        echo "Successfully uploaded build to Pie"
        echo "Response: $response"

branding:
  icon: "upload-cloud"
  color: "green"
