name: "Pie Build Uploader"
description: "Upload iOS/Android simulator builds to Pie"
author: "Pie"

inputs:
  pie_api_key:
    description: "Pie API Key for authentication"
    required: true
  build_path:
    description: "Path to the build file (APK, APP, or AAB)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check build file exists
      shell: bash
      id: build_check
      run: |
        if [ -d "${{ inputs.build_path }}" ]; then
          echo "Directory detected, creating zip archive..."
          dir_name=$(basename "${{ inputs.build_path }}")
          zip_path="${{ inputs.build_path }}.zip"
          cd "$(dirname "${{ inputs.build_path }}")"
          zip -r "$zip_path" "$dir_name"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to create zip archive"
            exit 1
          fi
          echo "Created zip archive at $zip_path"
          echo "build_path=$zip_path" >> $GITHUB_OUTPUT
        else
          echo "build_path=${{ inputs.build_path }}" >> $GITHUB_OUTPUT
        fi

    - name: Upload build to Pie
      shell: bash
      run: |
        build_path="${{ steps.build_check.outputs.build_path }}"

        if [ ! -f "$build_path" ]; then
          echo "Error: Build file not found at $build_path"
          exit 1
        fi

        # Check file extension
        if [[ ! "$build_path" =~ \.(apk|app|aab|zip)$ ]]; then
          echo "Error: Build file must be an APK, APP, AAB, or ZIP file"
          exit 1
        fi

        # Upload the build using curl with multipart form-data
        http_code=$(curl -X POST \
          -H "X-API-Key: ${{ inputs.pie_api_key }}" \
          -F "file=@$build_path" \
          -w "%{http_code}" \
          -s  -o /dev/null \
          https://api.pie.inc/v1/app/builds)

        # Check if curl command itself failed
        if [ $? -ne 0 ]; then
          echo "Error: Failed to upload build to Pie API - curl command failed"
          exit 1
        fi

        # Check for 201 Created status code
        if [ "$http_code" != "201" ]; then
          echo "Error: Failed to upload build to Pie API - received HTTP status code $http_code (expected 201 Created)"
          exit 1
        fi

        echo "Successfully uploaded build to Pie (HTTP status code: 201 Created)"

branding:
  icon: "upload-cloud"
  color: "green"
